config/routes.rb
Rails.application.routes.draw do
  root 'site/home#index'

  scope module: 'site' do
    get '/home', to: 'home#index'
  end

  scope module: 'backend' do
    get 'dashboard', to: 'dashboard#index'
    resources :users
    resources :episodes
    resources :sponsors
  end

  get '/login', to: 'backend/sessions#new'
  post '/login', to: 'backend/sessions#create'
  delete '/logout', to: 'backend/sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2 }
end

app/models/require_login.rb
module RequireLogin
  private

  def require_login
    unless logged_in?
      flash[:error] = "Please sign in first."
      redirect_to login_path
    end
  end
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2}
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, email:true, length: { minimum: 2 }
  validates :password, :presence => true, :length => {:within => 6..40}
  validates :twitter_username, presence: true, length: {minimum: 3}
  validates :github_username, presence: true, length: {minimum: 3}
  has_secure_password

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

      BCrypt::Password.create(string, cost: cost);
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticate?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_token, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Backend::SessionsHelper
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < ApplicationController
  include RequireLogin

  before_action :require_login
  layout 'backend/layouts/application'

  def index
    render 'index'
  end

end

app/controllers/backend/episodes_controller.rb
class Backend::EpisodesController < ApplicationController
  include RequireLogin

  before_action :require_login
  layout "backend/layouts/application"

  def index
    @episodes = Episode.all

    render 'index'
  end

  def new
    @episode = Episode.new

    render 'new'
  end

  def create
    @episode = Episode.new(episode_params)
    @episode['user_id'] = 1

    if @episode.save
      flash[:notice] = "Episode has been created."
      redirect_to @episode
    else
      flash.now[:alert] = "Episode has not been created."
      render 'new'
    end
  end

  def edit
    @episode = Episode.find(params[:id])

    render 'edit'
  end

  def show
    @episode = Episode.find(params[:id])

    render 'show'
  end

  def update
    @episode = Episode.find(params[:id])

    if @episode.update(episode_params)
      redirect_to @episode
    else
      render 'edit'
    end
  end

  def destroy
    @episode = Episode.find(params[:id])
    abort @episode.inspect
    @episode.destroy

    redirect_to episodes_path
  end

  private
  def episode_params
    params.require(:episode).permit(:title, :description, :audio_link, :links)
  end
end

app/controllers/backend/sessions_controller.rb
class Backend::SessionsController < ApplicationController

  def new
    render 'new'
  end

  def create
   user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
     log_in user
     params[:session][:remember_me] == '1' ? remember(user) : forget(user)
     flash[:success] = 'Congrats ! Login is successful'
     redirect_to user
   else
     flash.now[:danger] = 'Invalid email/password combination'
     render 'new'
   end
  end

  def destroy
    log_out if logged_in?
    redirect_to :root
  end
end

app/controllers/backend/sponsors_controller.rb
class Backend::SponsorsController < ApplicationController
  include RequireLogin

  before_action :require_login
  layout "backend/layouts/application"

  def index
    @sponsors = Sponsor.all

    render 'index'
  end

  def new
    @sponsor = Sponsor.new

    render 'new'
  end

  def create
    @sponsor = Sponsor.new(sponsor_params)

    if @sponsor.save
      flash[:notice] = 'Sponsor has been created ! Congrats'
      redirect_to @sponsor
    else
      flash[:alert] = 'Sponsor has not been created'
      render 'new'
    end
  end

  def edit
    @sponsor = Sponsor.find(params[:id])

    render 'edit'
  end

  def update
    @sponsor = Sponsor.find(params[:id])

    if @sponsor.update(sponsor_params)
      redirect_to @sponsor
    else
      render 'edit'
    end
  end

  def show
    @sponsor = Sponsor.find(params[:id])

    render 'show'
  end

  def destroy
    @sponsor = Sponsor.find(params[:id])
    @sponsor.destroy

    redirect_to sponsors_path
  end

  private
  def sponsor_params
    params.require(:sponsor).permit(:name, :link, :description, :logo_link)
  end

end

app/controllers/backend/users_controller.rb
class Backend::UsersController < ApplicationController
  include RequireLogin

  before_action :require_login
  layout "backend/layouts/application"

  def index
    @users = User.all

    render 'index'
  end

  def new
    @user = User.new

    render "new"
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User has been created."
      redirect_to @user
    else
      flash.now[:alert] = "User has not been created."
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])

    render 'edit'
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])

    render 'show'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :twitter_username, :github_username, :password)
  end

end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_errors(object, field_name)
    if object.errors.any?
      if !object.errors.messages[field_name].blank?
        object.errors.messages[field_name][0]
      end
    end
  end
end

app/helpers/backend/sessions_helper.rb
module Backend::SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/delete_link_helper.rb
module DeleteLinkHelper

  def delete_button_to(title, url, options = {})
    html_options = {
        class: "delete_button_to",
        method: "delete"
    }.merge(options.delete(:html_options) || {})

    form_for :delete, url: url, html: html_options do |f|
      f.submit title, options
    end
  end
end

app/views/backend/episodes/_form.html.erb
<div class="row gap-20 masonry pos-r">
  <div class="masonry-sizer col-md-6"></div>
  <div class="masonry-item col-md-12">
    <div class="bgc-white p-20 bd">
      <h6 class="c-grey-900"><%= action %> Episode</h6>
      <div class="mT-30">
        <%= form_for(@episode) do |form| %>
          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, :class => "form-control", :placeholder => "Title" %>
            <% if @episode.errors[:title] %>
              <div class="text-danger">
                <%=  show_errors(@episode, :title) %>
              </div>
            <% end %>
          </div>
          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area(:description, rows: 5, class: "form-control", placeholder: "Description") %>
            <div class="error">
              <%= show_errors(@episode, :description) %>
            </div>
          </div>
          <div class="form-group">
            <%= form.label :audio_link %>
            <%= form.text_field :audio_link, :class => "form-control", :placeholder => "Audio Link" %>
          </div>
          <div class="form-group">
            <%= form.label :links %>
            <%= form.text_area(:links, rows: 5, class: "form-control", placeholder: "Episode Description") %>
          </div>
          <%= form.submit :class => "btn btn-primary", :value => "Submit" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/backend/episodes/edit.html.erb
<%= render 'form', :action => 'Edit' %>

app/views/backend/episodes/index.html.erb
<div class="container-fluid"><h4 class="c-grey-900 mT-10 mB-30">Episodes</h4>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <p><%= link_to 'Create Episode', new_episode_path %></p>
        <table class="table table-bordered">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Audio Link</th>
            <th scope="col">Created By</th>
            <th scope="col">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @episodes.each do |episode, index| %>
            <tr>
              <td scope="row"><%= episode.id %></td>
              <td><%= episode.title %></td>
              <td><%= episode.description %></td>
              <td><%= episode.audio_link %></td>
              <td><%= User.find(episode.user_id).name %></td>
              <td>
                <div class="btn-group" role="group">
                  <button id="btnGroupDrop<%= index %>" type="button" class="btn cur-p bgc-white no-after dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="c-blue-500 fas fa-ellipsis-v"></i>
                  </button>
                  <ul class="dropdown-menu fsz-sm" aria-labelledby="btnGroupDrop<%= index %>" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 35px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <li><%= link_to "Show".html_safe, episode_path(episode), class: "d-b td-n pY-5 pX-10 bgcH-grey-100 c-grey-700" %></li>
                    <li><%= link_to "Edit".html_safe, edit_episode_path(episode), class: "d-b td-n pY-5 pX-10 bgcH-grey-100 c-grey-700" %></li>
                    <li><%= button_to "Delete", episode, method: :delete,
                      data: { confirm: "Are you sure to delete episode?" }, class: 'd-b td-n pY-5 pX-10 bgcH-grey-100 c-grey-700' %></li>
                  </ul>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/backend/episodes/new.html.erb
<%= render 'form', :action => 'Create' %>

app/views/backend/episodes/show.html.erb
<tr>
  <td><%= @episode.title %></td>
  <td><%= @episode.description %></td>
  <td><%= @episode.audio_link %></td>
  <td><%= @episode.links %></td>
  <td><%= link_to 'Go Back Man', episodes_path %></td>
</tr>

app/views/backend/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Dashboard</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'backend/admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'backend' %>

  <style>
    #loader {
      transition: all 0.3s ease-in-out;
      opacity: 1;
      visibility: visible;
      position: fixed;
      height: 100vh;
      width: 100%;
      background: #fff;
      z-index: 90000;
    }

    #loader.fadeOut {
      opacity: 0;
      visibility: hidden;
    }

    .spinner {
      width: 40px;
      height: 40px;
      position: absolute;
      top: calc(50% - 20px);
      left: calc(50% - 20px);
      background-color: #333;
      border-radius: 100%;
      -webkit-animation: sk-scaleout 1.0s infinite ease-in-out;
      animation: sk-scaleout 1.0s infinite ease-in-out;
    }

    @-webkit-keyframes sk-scaleout {
      0% {
        -webkit-transform: scale(0)
      }
      100% {
        -webkit-transform: scale(1.0);
        opacity: 0;
      }
    }

    @keyframes sk-scaleout {
      0% {
        -webkit-transform: scale(0);
        transform: scale(0);
      }
      100% {
        -webkit-transform: scale(1.0);
        transform: scale(1.0);
        opacity: 0;
      }
    }
  </style>
</head>
<body class="app">
<div id='loader'>
  <div class="spinner"></div>
</div>

<script>
  window.addEventListener('load', () => {
    const loader = document.getElementById('loader');
    setTimeout(() => {
      loader.classList.add('fadeOut');
    }, 300);
  });
</script>

<!-- @App Content -->
<!-- =================================================== -->
<div>
  <!-- #Left Sidebar ==================== -->
  <%= render 'backend/partials/sidebar' %>

  <!-- #Main ============================ -->
  <div class="page-container">
    <!-- ### $Topbar ### -->
    <%= render 'backend/partials/navbar' %>

    <main class='main-content bgc-grey-100'>
      <div id='mainContent'>
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
      </div>
    </main>

    <!-- ### $App Screen Footer ### -->
    <footer class="bdT ta-c p-30 lh-0 fsz-sm c-grey-600">
      <span>Copyright © 2017 Designed by <a href="https://colorlib.com" target='_blank' title="Colorlib">Colorlib</a>. All rights reserved.</span>
    </footer>
  </div>
</div>
</body>
</html>

app/views/backend/partials/_navbar.html.erb
<div class="header navbar">
  <div class="header-container">
    <ul class="nav-left">
      <li>
        <a id='sidebar-toggle' class="sidebar-toggle" href="javascript:void(0);">
          <i class="fas fa-bars"></i>
        </a>
      </li>
      <li class="search-box">
        <a class="search-toggle no-pdd-right" href="javascript:void(0);">
          <i class="search-icon ti-search pdd-right-10"></i>
          <i class="search-icon-close ti-close pdd-right-10"></i>
        </a>
      </li>
      <li class="search-input">
        <input class="form-control" type="text" placeholder="Search...">
      </li>
    </ul>

    <ul class="nav-right">
  <li class="notifications dropdown">
    <span class="counter bgc-red">3</span>
    <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
      <i class="fas fa-bell"></i>
    </a>

    <ul class="dropdown-menu">
      <li class="pX-20 pY-15 bdB">
        <i class="ti-bell pR-10"></i>
        <span class="fsz-sm fw-600 c-grey-900">Notifications</span>
      </li>
      <li>
        <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
          <li>
            <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
              <div class="peer mR-15">
                <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
              </div>
              <div class="peer peer-greed">
                            <span>
                              <span class="fw-500">John Doe</span>
                              <span class="c-grey-600">liked your <span class="text-dark">post</span>
                              </span>
                            </span>
                <p class="m-0">
                  <small class="fsz-xs">5 mins ago</small>
                </p>
              </div>
            </a>
          </li>
          <li>
            <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
              <div class="peer mR-15">
                <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
              </div>
              <div class="peer peer-greed">
                            <span>
                              <span class="fw-500">Moo Doe</span>
                              <span class="c-grey-600">liked your <span class="text-dark">cover image</span>
                              </span>
                            </span>
                <p class="m-0">
                  <small class="fsz-xs">7 mins ago</small>
                </p>
              </div>
            </a>
          </li>
          <li>
            <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
              <div class="peer mR-15">
                <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
              </div>
              <div class="peer peer-greed">
                            <span>
                              <span class="fw-500">Lee Doe</span>
                              <span class="c-grey-600">commented on your <span class="text-dark">video</span>
                              </span>
                            </span>
                <p class="m-0">
                  <small class="fsz-xs">10 mins ago</small>
                </p>
              </div>
            </a>
          </li>
        </ul>
      </li>
      <li class="pX-20 pY-15 ta-c bdT">
                    <span>
                      <a href="" class="c-grey-600 cH-blue fsz-sm td-n">View All Notifications <i class="ti-angle-right fsz-xs mL-10"></i></a>
                    </span>
      </li>
    </ul>
  </li>
  <li class="notifications dropdown">
    <span class="counter bgc-blue">3</span>
    <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
      <i class="fas fa-envelope-open"></i>
    </a>

    <ul class="dropdown-menu">
      <li class="pX-20 pY-15 bdB">
        <i class="ti-email pR-10"></i>
        <span class="fsz-sm fw-600 c-grey-900">Emails</span>
      </li>
      <li>
        <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
          <li>
            <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
              <div class="peer mR-15">
                <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
              </div>
              <div class="peer peer-greed">
                <div>
                  <div class="peers jc-sb fxw-nw mB-5">
                    <div class="peer">
                      <p class="fw-500 mB-0">John Doe</p>
                    </div>
                    <div class="peer">
                      <small class="fsz-xs">5 mins ago</small>
                    </div>
                  </div>
                  <span class="c-grey-600 fsz-sm">
                                Want to create your own customized data generator for your app...
                              </span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
              <div class="peer mR-15">
                <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
              </div>
              <div class="peer peer-greed">
                <div>
                  <div class="peers jc-sb fxw-nw mB-5">
                    <div class="peer">
                      <p class="fw-500 mB-0">Moo Doe</p>
                    </div>
                    <div class="peer">
                      <small class="fsz-xs">15 mins ago</small>
                    </div>
                  </div>
                  <span class="c-grey-600 fsz-sm">
                                Want to create your own customized data generator for your app...
                              </span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
              <div class="peer mR-15">
                <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
              </div>
              <div class="peer peer-greed">
                <div>
                  <div class="peers jc-sb fxw-nw mB-5">
                    <div class="peer">
                      <p class="fw-500 mB-0">Lee Doe</p>
                    </div>
                    <div class="peer">
                      <small class="fsz-xs">25 mins ago</small>
                    </div>
                  </div>
                  <span class="c-grey-600 fsz-sm">
                                Want to create your own customized data generator for your app...
                              </span>
                </div>
              </div>
            </a>
          </li>
        </ul>
      </li>
      <li class="pX-20 pY-15 ta-c bdT">
                    <span>
                      <a href="email.html" class="c-grey-600 cH-blue fsz-sm td-n">View All Email <i class="fs-xs ti-angle-right mL-10"></i></a>
                    </span>
      </li>
    </ul>
  </li>
  <% if logged_in? %>
    <li class="dropdown">
      <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
        <div class="peer">
          <span class="fsz-sm c-grey-900"><%= current_user.name %></span>
        </div>
      </a>
      <ul class="dropdown-menu fsz-sm">
        <li>
          <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
            <i class="fas fa-cog mR-10"></i>
            <span>Setting</span>
          </a>
        </li>
        <li>
          <%= link_to "<i class='fas fa-user mR-10'></i><span>Profile</span>".html_safe, user_path(current_user), class: 'd-b td-n pY-5 bgcH-grey-100 c-grey-700' %>
        </li>
        <li role="separator" class="divider"></li>
        <li>
          <%= button_to "Logout", logout_path, method: :delete,
                        data: {confirm: "Are you sure to Logout?"}, class: 'd-b td-n pY-5 bgcH-grey-100 c-grey-700 text-center' %>
        </li>
      </ul>
    </li>
  <% end %>
</ul>
</div>
</div>

app/views/backend/sponsors/edit.html.erb
<%= render 'form', :action => 'Edit' %>

app/views/backend/sponsors/index.html.erb
<div class="container-fluid"><h4 class="c-grey-900 mT-10 mB-30">Sponsors</h4>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <p><%= link_to 'Create Sponsor', new_sponsor_path %></p>
        <table class="table table-bordered">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Logo</th>
            <th scope="col">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @sponsors.each do |sponsor, index| %>
            <tr>
              <td scope="row"><%= sponsor.id %></td>
              <td><%= sponsor.name %></td>
              <td><%= sponsor.description %></td>
              <td><%= image_tag(sponsor.logo_link , :alt => "rss feed", :height => "50px", :width => "50px") %></td>
              <td>
                <div class="btn-group" role="group">
                  <button id="btnGroupDrop<%= index %>" type="button" class="btn cur-p bgc-white no-after dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="c-blue-500 fas fa-ellipsis-v"></i>
                  </button>
                  <ul class="dropdown-menu fsz-sm" aria-labelledby="btnGroupDrop<%= index %>" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 35px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <li><%= link_to "Show".html_safe, sponsor_path(sponsor), class: "d-b td-n pY-5 pX-10 bgcH-grey-100 c-grey-700" %></li>
                    <li><%= link_to "Edit".html_safe, edit_sponsor_path(sponsor), class: "d-b td-n pY-5 pX-10 bgcH-grey-100 c-grey-700" %></li>
                    <li><%= button_to "Delete", sponsor, method: :delete,
                      data: {confirm: "Are you sure to delete episode?"}, class: 'd-b td-n pY-5 pX-10 bgcH-grey-100 c-grey-700' %></li>
                  </ul>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/backend/sponsors/new.html.erb
<%= render 'form', :action => 'Create' %>

app/views/backend/sponsors/show.html.erb
<tr>
  <td><%= @sponsor.name %></td>
  <td><%= @sponsor.link %></td>
  <td><%= @sponsor.description %></td>
  <td><%= @sponsor.logo_link %></td>
  <td><%= link_to 'GO Back', sponsors_path %></td>
</tr>

app/views/backend/users/edit.html.erb
<%= render 'form', :action => 'Edit' %>

app/views/backend/users/index.html.erb
<div class="container-fluid"><h4 class="c-grey-900 mT-10 mB-30">Episodes</h4>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <p><%= link_to 'Create User', new_user_path %></p>
        <table class="table table-bordered">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Twitter Username</th>
            <th scope="col">Github Username</th>
            <th scope="col">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @users.each do |user, index| %>
            <tr>
              <td scope="row"><%= user.id %></td>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.twitter_username %></td>
              <td><%= user.github_username %></td>
              <td>
                <div class="btn-group" role="group">
                  <button id="btnGroupDrop<%= index %>" type="button" class="btn cur-p bgc-white no-after dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="c-blue-500 fas fa-ellipsis-v"></i>
                  </button>
                  <ul class="dropdown-menu fsz-sm" aria-labelledby="btnGroupDrop<%= index %>" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 35px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <li><%= link_to "Show", user_path(user), class: "d-b td-n pY-5 pX-10 bgcH-grey-100 c-grey-700" %></li>
                    <li><%= link_to "Edit", edit_user_path(user), class: "d-b td-n pY-5 pX-10 bgcH-grey-100 c-grey-700" %></li>
                    <li><%= button_to "Delete", user, method: :delete,
                      data: {confirm: "Are you sure to delete episode?"}, class: 'd-b td-n pY-5 pX-10 bgcH-grey-100 c-grey-700' %></li>
                  </ul>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/backend/users/new.html.erb
<%= render 'form', :action => 'Create' %>

app/views/backend/users/show.html.erb
<tr>
  <td><%= @user.name %></td>
  <td><%= @user.email %></td>
  <td><%= @user.twitter_username %></td>
  <td><%= @user.github_username %></td>
  <td><%= link_to 'Go Back Man', users_path %></td>
</tr>

app/views/site/home/index.html.erb
<h2>This one the the front end site, Will upgrade later HEHEEHEHEHEHHEHEH</h2>